### ISSUE TITLE
connection.close does not always free up resources 

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#136]
Please see https://github.com/ably/ably-js/commit/d5fc19a327bde198126238bbb824a9b019cae99a, and then run the test locally with Node.js as follows:

```
$ grunt test:nodeunit --test spec/realtime/failure.test.js

failure.test.js
Test App bWQARA in environment sandbox has been set up
✔ setupFailure
Ably: Connection.connect():
Ably: ConnectionManager.chooseTransport():
req error: Error: getaddrinfo ENOTFOUND this.does.not.exist this.does.not.exist:443
    at errnoException (dns.js:25:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
Ably: ConnectionManager.chooseTransport(): Unexpected error establishing transport; err = {"statusCode":404,"code":80000}
Ably: ConnectionManager.connectImpl(): Connection attempt failed with error; err = [ErrorInfo; statusCode=404; code=80000]
Ably: Connection.close(): connectionKey = undefined
✔ ensure_resources_freed_after_failure

tear_down.js
Test App bWQARA has been torn down
✔ teardownapp

OK: 4 assertions (5124ms)
>> Nodeunit tests passed

Done, without errors.
```

Whilst the test passes, it takes around 60s after `ensure_resources_freed_after_failure` has passed for node.js to exit.  Thus, I think that we are not freeing up the Ably Realtime resources correctly when `client.close()` is called.

**Comment by mattheworiordan** [comment]
Fixed with https://github.com/ably/ably-js/commit/62a813aa2463b10fd939875fcf1b575fd53d0a0a
