### ISSUE TITLE
is ably react hooks supported in nextjs edge run time? [window is not defined]

### ISSUE THREAD

**Issue by matannahmani** [ably/ably-js#1456]
I've tried to import the client in different ways but all result in the same problem of window is not defined.
My current implementation:
```"use client";
import { AblyProvider as AblyProviderBase } from "ably/react";
import { useEffect, useState } from "react";
import { ablyClient } from "~/shared/ably/ably";

export default function AblyProvider({
  children,
}: {
  children: React.ReactNode;
}) {
  const [loaded, setLoaded] = useState(false);
  useEffect(() => {
    setLoaded(true);
  }, []);
  if (!loaded) return children;
  return <AblyProviderBase client={ablyClient}>{children}</AblyProviderBase>;
}
```

and then consume it with:
```
import dynamic from "next/dynamic";
const AblyProvider = dynamic(
  () => import("~/components/providers/AblyProvider"),
  {
    ssr: false,
  },
);
```

but i keep getting errors and page crashes:
```
 ⨯ ReferenceError: window is not defined
    at __webpack_require__ (/home/matan/code/down-to-eat/.next/server/edge-runtime-webpack.js:37:33)
    at fn (/home/matan/code/down-to-eat/.next/server/edge-runtime-webpack.js:330:21)
    at __webpack_require__ (/home/matan/code/down-to-eat/.next/server/edge-runtime-webpack.js:37:33)
    at fn (/home/matan/code/down-to-eat/.next/server/edge-runtime-webpack.js:330:21)
```

**Comment by matannahmani** [comment]
managed to fix this, I think it would be good to make an official documentation of basic implementation.
my issue was the ablyClient, it must be initiated inside a client component inside the react tree.
to fix it you can create a provider as follows:

export default function AblyProvider({
  children,
}: {
  children: React.ReactNode;
}) {
  const [client, _] = useState(
    new Realtime.Promise({
      key: env.NEXT_PUBLIC_ABLY_CLIENT_API_KEY,
    }),
  );
  return <AblyProviderBase client={client}>{children}</AblyProviderBase>;
}
