### ISSUE TITLE
require('ably') fails

### ISSUE THREAD

**Issue by sguron** [ably/ably-js#262]
Readme suggests suggests to import ably as
var Ably = require('ably-js');

This fails as follows

```
~$ node ablytest.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'ably-js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ubuntu/ablytest.js:1:74)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

what seems to be working
var Ably = require('ably');

On a secondary maybe even more important note, build is failing on travis. npn doesnt properly install ably. The only way i got it to install was directly pulling ably from git.

**Comment by SimonWoolf** [comment]
> require('ably-js');

Good spot, thanks. I've updated the readme with the correct npm package name (I think we changed it a while ago).

> build is failing on travis.

This is a due to a change in an obscure part of the stats request format making some stats tests fail; it's known and will be fixed soon.

> npn doesnt properly install ably

Hmm, 'npm install ably' works fine for me over here. What fails for you? (Also what version of node are you running?)
