### ISSUE TITLE
Browser test error: authbase0 - displayError is not defined

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#35]
Running:
`$ grunt nodeunit:webserver`

against sanbox I get the following error:

### authbase0

```
Ably: Connection.connect(): 
ably.js:4067 Ably: ConnectionManager.chooseTransport(): 
sandbox-rest.ably.io/keys/Gl1N4Q.lCxqBQ/requestToken?rnd=6598727754317224:1 POST https://sandbox-rest.ably.io/keys/Gl1N4Q.lCxqBQ/requestToken?rnd=6598727754317224 401 (Unauthorized)
ably.js:4067 Ably: Auth.requestToken(): token request API call returned error; err = {"statusCode":401,"code":40101,"message":"No key id specified"}
ably.js:4067 Ably: EventEmitter.emit(): Unexpected listener exception: ReferenceError: displayError is not defined; stack = ReferenceError: displayError is not defined
    at http://localhost:3000/spec/realtime/auth.test.js:36:24
    at Object.<anonymous> (http://localhost:3000/browser/static/ably.js:6632:6)
    at callListener (http://localhost:3000/browser/static/ably.js:4022:19)
    at XHRRequest.EventEmitter.emit (http://localhost:3000/browser/static/ably.js:4039:5)
    at XHRRequest.complete (http://localhost:3000/browser/static/ably.js:8103:9)
    at onEnd (http://localhost:3000/browser/static/ably.js:8211:9)
    at XMLHttpRequest.XHRRequest.exec.xhr.onreadystatechange (http://localhost:3000/browser/static/ably.js:8260:7)
```

I realise sandbox is not in sync, but the error about displayError seems to be a bug.

**Comment by paddybyers** [comment]
Fixed: https://github.com/ably/ably-js/commit/4e65d4e

**Comment by paddybyers** [comment]
resolved
