### ISSUE TITLE
authUrl causing Node.js app crash

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#354]
From a customer:

> If I stop process on the `authUrl` server making the server (tokens) unavailable. The below is the output from a the app when it crashes. I think its when he app tries to get a new token before it expires.

```
/app/ably/nodejs/node_modules/ably-js-0-9-spec/common/lib/transport/connectionmanager.js:1171
            accessToken: tokenDetails.token
                                     ^
TypeError: Cannot read property 'token' of undefined
    at ConnectionManager.onAuthUpdated (/app/ably/nodejs/node_modules/ably-js-0-9-spec/common/lib/transport/connectionmanager.js:1171:32)
    at /app/ably/nodejs/node_modules/ably-js-0-9-spec/common/lib/client/auth.js:188:46
    at /app/ably/nodejs/node_modules/ably-js-0-9-spec/common/lib/client/auth.js:220:4
    at /app/ably/nodejs/node_modules/ably-js-0-9-spec/common/lib/client/auth.js:646:6
    at /app/ably/nodejs/node_modules/ably-js-0-9-spec/common/lib/client/auth.js:391:5
    at authUrlRequestCallback (/app/ably/nodejs/node_modules/ably-js-0-9-spec/common/lib/client/auth.js:313:33)
    at Request._callback (/app/ably/nodejs/node_modules/ably-js-0-9-spec/nodejs/lib/util/http.js:24:5)
    at self.callback (/app/ably/nodejs/node_modules/ably-js-0-9-spec/node_modules/request/request.js:186:22)
    at Request.emit (events.js:107:17)
    at Request.onRequestError (/app/ably/nodejs/node_modules/ably-js-0-9-spec/node_modules/request/request.js:845:8)
```

**Comment by SimonWoolf** [comment]
[Fixed by 0.9.0-beta4](https://github.com/ably/ably-js/commit/65ad91ee3b800ea18e9589da4b0d56fdd70d2798).
