### ISSUE TITLE
Regular JS errors appearing

### ISSUE THREAD

**Issue by wichert** [ably/ably-js#360]
I seem to get this error reasonably regular in our logs. This is on an application that only subscribes to a single channel, and never publishes anything. Ably version is 0.8.41.

```
Ably: WebSocketTransport.onWsData(): Unexpected exception handing channel message: TypeError: Cannot read property 'data' of undefined
at _Service.onAblyMessage (/home/pi/eventbots-os/node_modules/tiki-package-signup/main/service.coffee:312:77)
at EventEmitter.emit (/home/pi/eventbots-os/node_modules/ably/common/lib/util/eventemitter.js:145:16)
at RealtimeChannel.onEvent (/home/pi/eventbots-os/node_modules/ably/common/lib/client/realtimechannel.js:109:18)
at RealtimeChannel.onMessage (/home/pi/eventbots-os/node_modules/ably/common/lib/client/realtimechannel.js:328:9)
at Channels.onChannelMessage (/home/pi/eventbots-os/node_modules/ably/common/lib/client/realtime.js:53:11)
at ConnectionManager.onChannelMessage (/home/pi/eventbots-os/node_modules/ably/common/lib/transport/connectionmanager.js:1281:27)
at WebSocketTransport.Transport.onProtocolMessage (/home/pi/eventbots-os/node_modules/ably/common/lib/transport/transport.js:112:27)
at WebSocketTransport.onWsData (/home/pi/eventbots-os/node_modules/ably/common/lib/transport/websockettransport.js:90:9)
at WebSocket.wsConnection.onmessage (/home/pi/eventbots-os/node_modules/ably/common/lib/transport/websockettransport.js:68:50)
at WebSocket.onMessage (/home/pi/eventbots-os/node_modules/ws/lib/WebSocket.js:442:14)
at emitTwo (events.js:106:13)
at WebSocket.emit (events.js:191:7)
at Receiver.ontext (/home/pi/eventbots-os/node_modules/ws/lib/WebSocket.js:841:10)
at /home/pi/eventbots-os/node_modules/ws/lib/Receiver.js:536:18
at Receiver.applyExtensions (/home/pi/eventbots-os/node_modules/ws/lib/Receiver.js:371:5)
at /home/pi/eventbots-os/node_modules/ws/lib/Receiver.js:508:14
at Receiver.flush (/home/pi/eventbots-os/node_modules/ws/lib/Receiver.js:347:3)
at Receiver.finish (/home/pi/eventbots-os/node_modules/ws/lib/Receiver.js:541:12)
at Receiver.expectHandler (/home/pi/eventbots-os/node_modules/ws/lib/Receiver.js:499:31)
at Receiver.add (/home/pi/eventbots-os/node_modules/ws/lib/Receiver.js:103:24)
at TLSSocket.realHandler (/home/pi/eventbots-os/node_modules/ws/lib/WebSocket.js:825:20)
at emitOne (events.js:96:13)
at TLSSocket.emit (events.js:188:7)
at readableAddChunk (_stream_readable.js:176:18)
at TLSWrap.onread (net.js:551:20)
```

**Comment by wichert** [comment]
Some useful information: the `_Service.onAblyMessage` code looks like this:

```
  onAblyMessage: (msg) ->
    winston.verbose 'Received an ably message', {ably: msg}
    if !@manager.current
      return

    if msg.data.session
      @sessions.setActiveSession msg.data.session
      @sessions.touch msg.data.session
```

And the Ably configuration code is:

```
  startAbly: (config) ->
    channel = config.ably.channel
    return new Promise (resolve, reject) =>
      @ably_client = new ably.Realtime {
        authUrl: config.ably.auth_url,
        authHeaders: {'x-api-key': config.aws.api_key}
      }
      @ably_client.connection.on 'connected', () =>
        winston.info 'Ably connection (re)established'
        _.each @ably_client.channels.all, (params, name) =>
          @ably_client.channels.get(name).attach()

      @ably_client.connection.on 'disconnected', () =>
        winston.warn 'Ably disconnect'
        @sentry.captureMessage 'Ably disconnected'
      @ably_client.connection.on 'suspended', () =>
        winston.warn 'Lost connection to Ably, will retry in 2 minutes'
        @sentry.captureMessage 'Lost connection to Ably, will retry in 2 minutes'
      @ably_client.connection.on 'failed', () =>
        winston.error 'Ably connection failed completely'
        @sentry.captureMessage 'Ably connection failed completely'

      @ably_channel = @ably_client.channels.get channel
      @ably_channel.attach (e) =>
        if (e)
          winston.warn 'Ably attached failure for channel ' + channel
          @sentry.captureMessage('Ably attached failure for channel ' + channel)
          reject(e)
        else
          winston.info 'Attached to Ably channel ' + channel
          resolve()
      @ably_channel.on 'detached', () =>
        if @ably_client && @ably_client.connected.state == 'connected' && @ably_channel
          @ably_channel.attach()
      @ably_channel.on 'failed', () =>
        winston.warn 'Ably channel attach failed for ' + channel
        @sentry.captureMessage('Ably channel attach failed')
```

**Comment by SimonWoolf** [comment]
Hi @wichert. That's curious -- seems to indicate that the `onAblyMessage` handler is being called with `msg` undefined, which shouldn't be possible.

Would you mind pasting in the part of your code which calls subscribe() to add that `onAblyMessage` handler? Can't see that bit in the code you posted.

Additionally, if possible, if you could reproduce this with debug-level logging (`log: {level: 4}` in the lib initializer) switched on to capture the log of this happening, that'd be awesome

**Comment by wichert** [comment]
The subscribe call was elsewhere in the code. After the promise returned on `startAbly` is resolved this is called:

```coffeescript
@ably_channel.subscribe @onAblyMessage.bind(this)
```

I have enabled debug-level debugging. Unfortunately I won't have access to our robot hardware for the next few days, so I don't know if I can reproduce this quickly. I will try on the simulator.

**Comment by SimonWoolf** [comment]
Thanks -- that all looks fine as far as I can see. Best of luck getting the logging; hopefully that'll tell us what's going on. (You might also want to turn the severity level of your `Received an ably message, {ably: msg}` message up as well as the client lib log level)

**Comment by SimonWoolf** [comment]
Hi @wichert. Hope you had a good holiday season. Any update on whether you could reproduce this with debug-level logging enabled?

**Comment by wichert** [comment]
@SimonWoolf I did see this today actually, but on a bot that did not have the debug logging enabled unfortunately. It would be convenient if I could use a separate logger (like a winston instance) for Ably to prevent cluttering our normal logs. Is that possible?

**Comment by SimonWoolf** [comment]
@wichert Yup, you can do that by specifying a `handler` in the `log` object in the clientOptions, which should be a function that takes a string argument: `new Ably.Realtime({ log: { level: 4, handler: function(logMessage) { ... } }, ... })`

**Comment by wichert** [comment]
I think I found the source for this error, and it is entirely my fault: my code had a dot instead of a comma. The fix is very simple:

```
             when 'input-focus'
-              @manager.current.onBrowserInputFocus msg.data.input. msg.data
+              @manager.current.onBrowserInputFocus msg.data.input, msg.data
```

**Comment by SimonWoolf** [comment]
Cool, glad you found it :)
