### ISSUE TITLE
Fail pending messages fails if the connection is closed

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#381]
When running the debug tests on the website, I see:

```
1488902667075 [log] Ably: RealtimeChannel.failPendingMessages: channel; name = TLw0F, err = [ErrorInfo: Connection closed; statusCode=408; code=80017]
    at Object.console.(anonymous function) [as log] (http://localhost:3000/assets/pages/debug.self-50a362ee47cba690d3930f95b0292a4b3685cf29606ca4328a9f5decd57c117b.js?body=1:58:63)
    at consoleLogger (http://cdn.ably.io/lib/ably.js:4326:44)
    at Function.Logger.logAction (http://cdn.ably.io/lib/ably.js:4364:4)
    at RealtimeChannel.failPendingMessages (http://cdn.ably.io/lib/ably.js:9465:10)
    at RealtimeChannel.setSuspended (http://cdn.ably.io/lib/ably.js:9367:9)
    at Channels.setSuspended (http://cdn.ably.io/lib/ably.js:8709:12)
    at ConnectionManager.notifyState (http://cdn.ably.io/lib/ably.js:6349:27)
    at ConnectionManager.deactivateTransport (http://cdn.ably.io/lib/ably.js:6077:9)
    at Object.<anonymous> (http://cdn.ably.io/lib/ably.js:5807:10)
    at callListener (http://cdn.ably.io/lib/ably.js:4130:13)
```

**Comment by SimonWoolf** [comment]
Sorry, I don't understand what the bug is. Surely we do want to fail pending messages if the connection is closed -- it's spec item [RTN7c](https://docs.ably.io/client-lib-development-guide/features/#RTN7c).

**Comment by mattheworiordan** [comment]
@SimonWoolf ah, I missed the line `Object.console.(anonymous function) [as log] (http://localhost:3000/assets/pa...` which indicates the error is being logged by the website code, not the client lib. Sorry, didn't look at that properly
