### ISSUE TITLE
WsData exception

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#61]
When connecting, disconnecting, and reconnecting, I have seen this in the logs:

```
Ably: Connection.close(): connectionKey = cMK2riyOP3djUQZ9
ably.min.js:65 Ably: Connection.connect(): 
ably.min.js:65 Ably: ConnectionManager.chooseTransport(): 
ably.min.js:65 Ably: ConnectionManager.chooseTransport(): upgrading ... connectionKey = vZjDR44PIHjNnzUA
ably.min.js:65 Ably: WebSocketTransport.onWsData(): Unexpected exception handing channel message: TypeError: Cannot read property 'length' of undefined
    at c.onMessage (https://cdn.ably.io/lib/ably.min.js:167:45)
    at l.onChannelMessage (https://cdn.ably.io/lib/ably.min.js:150:411)
    at b.onChannelMessage (https://cdn.ably.io/lib/ably.min.js:114:178)
    at c.onChannelMessage (https://cdn.ably.io/lib/ably.min.js:118:214)
    at c.onWsData (https://cdn.ably.io/lib/ably.min.js:123:253)
    at WebSocket.c.connect.auth.getAuthParams.p.onmessage (https://cdn.ably.io/lib/ably.min.js:122:461)
```

**Comment by mattheworiordan** [comment]
Please note that the connection settings are as follows:

```javascript
var client = new Ably.Realtime({
        authUrl: this.authUrl
      });
```

**Comment by paddybyers** [comment]
A stack trace with ably.js would be great :)

**Comment by mattheworiordan** [comment]
What do you mean?  That is all that is in the console?

**Comment by paddybyers** [comment]
I mean run it with ably.js instead of ably-min.js

**Comment by mattheworiordan** [comment]
Ok, will do that
