### ISSUE TITLE
Error when trying to connect on nodejs: Unexpected exception creating websocket

### ISSUE THREAD

**Issue by yan-ts** [ably/ably-js#669]
I am trying to run ably Realtime on nodejs.
My system's specs:
Orange Pi PC (arm)
debian 9
ably v1.2.1,
node v12.18.1
npm v6.14.5

I am trying to run this simple code:

> var ably = new require('ably').Realtime('MyApiKey');  
> var channel = ably.channels.get('test');  
> ably.connection.on('connected', function() {  
>   console.log('Connected');  
> })

But I get the following error:
`14:14:44.412 Ably: WebSocketTransport.connect(): Unexpected exception creating websocket: err = TypeError: Limiter is not a constructor
    at new PerMessageDeflate (/root/pubsub/node_modules/ws/lib/permessage-deflate.js:71:21)
    at WebSocket.initAsClient (/root/pubsub/node_modules/ws/lib/websocket.js:480:25)
    at new WebSocket (/root/pubsub/node_modules/ws/lib/websocket.js:62:20)
    at WebSocketTransport.createWebSocket (/root/pubsub/node_modules/ably/common/lib/transport/websockettransport.js:41:10)
    at /root/pubsub/node_modules/ably/common/lib/transport/websockettransport.js:67:49
    at Auth.getAuthParams (/root/pubsub/node_modules/ably/common/lib/client/auth.js:618:4)
    at WebSocketTransport.connect (/root/pubsub/node_modules/ably/common/lib/transport/websockettransport.js:55:13)
    at Function.WebSocketTransport.tryConnect (/root/pubsub/node_modules/ably/common/lib/transport/websockettransport.js:31:13)
    at ConnectionManager.tryATransport (/root/pubsub/node_modules/ably/common/lib/transport/connectionmanager.js:274:54)
    at ConnectionManager.connectBase (/root/pubsub/node_modules/ably/common/lib/transport/connectionmanager.js:1316:8)
14:14:44.428 Ably: EventEmitter.emit(): Unexpected listener exception: TypeError: extend is not a function; stack = TypeError: extend is not a function
    at initParams (/root/pubsub/node_modules/request/index.js:35:5)
    at Function.get (/root/pubsub/node_modules/request/index.js:59:18)
    at Function.Http.Http.doUri (/root/pubsub/node_modules/ably/nodejs/lib/util/http.js:187:18)
    at Function.Http.<computed> [as getUri] (/root/pubsub/node_modules/ably/nodejs/lib/util/http.js:107:9)
    at Function.Http.Http.checkConnectivity (/root/pubsub/node_modules/ably/nodejs/lib/util/http.js:195:8)
    at tryFallbackHosts (/root/pubsub/node_modules/ably/common/lib/transport/connectionmanager.js:1288:9)
    at hostAttemptCb (/root/pubsub/node_modules/ably/common/lib/transport/connectionmanager.js:1264:6)
    at /root/pubsub/node_modules/ably/common/lib/transport/connectionmanager.js:306:6
    at Object.errorCb (/root/pubsub/node_modules/ably/common/lib/transport/websockettransport.js:24:33)
    at callListener (/root/pubsub/node_modules/ably/common/lib/util/eventemitter.js:14:13)`

What could it be?

**Comment by SimonWoolf** [comment]
Looks like you're missing several dependencies. Did you get any errors when running `npm install`?

**Comment by yan-ts** [comment]
> Looks like you're missing several dependencies. Did you get any errors when running `npm install`?

I didn't get any error on `npm install`.
But you were right about the dependencies, I started a new project with ably alone - and it worked on this machine.
I'll have to dig deeper to check which package is causing this issue.

Thanks.
