### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'bind') in browser

### ISSUE THREAD

**Issue by tencircles** [ably/ably-js#882]
When using the ably in the browser the following error occurs when the library is imported. I am using nextjs and deploying on vercel, but I don't believe that should cause this issue.

`TypeError: Cannot read properties of undefined (reading 'bind')`

Is the library not meant for use on the client side? I'm a bit confused.

**Comment by owenpearson** [comment]
Hi @tencircles, thanks for reporting this. The library should generally work fine on the client side. To help us understand what's causing this issue we would need some more information to help with our investigation. In particular we would like to know:
- What version of NextJS and Ably are you using?
- Which web browser are you seeing the error in?
- Does the error message come with a stack trace? If so could you post it here in the comments?

**Comment by tencircles** [comment]
Hey there @owenpearson .

I have tried Ably `^1.2.18-beta.0` and `^1.2.17` both produce the same error.
I am using next version `12.0.8`.
I am seeing the error in chrome, safari, and FF.

Below is a stack trace. 

```
index.js:430 TypeError: Cannot read properties of undefined (reading 'bind')
    at Object.<anonymous> (ably-commonjs.js:829:1)
    at Object.<anonymous> (ably-commonjs.js:858:85)
    at c (ably-commonjs.js:42:1)
    at Module.<anonymous> (ably-commonjs.js:12377:1)
    at c (ably-commonjs.js:42:1)
    at ably-commonjs.js:106:11
    at ably-commonjs.js:107:1
    at ably-commonjs.js:20:28
    at Object.8351 (ably-commonjs.js:22:1)
    at g (bootstrap:22:1)
```

It seems to be pointing at this line

`nextTick: typeof setImmediate !== 'undefined' ? global.setImmediate.bind(global) : function(f) { setTimeout(f, 0); },`

Here the value of `setImmediate.bind` is `undefined` causing the above error.
I can only think of two causes.

1. Something in nextjs or webpack is modifying Function.prototype (very unlikely).
2. The value of `global` in the browser is referencing something other than `window`.

Any input is appreciated.

**Comment by tencircles** [comment]
Potential third cause would be something overwriting `window.setImmediate` with something other than a function, but just a quick check in the console reveals this not to be the case.

**Comment by owenpearson** [comment]
Thanks for getting back to us @tencircles. FYI the error message you're seeing indicates that `global.setImmediate` is not defined (not just `global.setImmediate.bind`). What strikes me as odd is that for the browser to reach that branch `typeof setImmediate !== 'undefined'` must evaluate to `true`. Webpack sets `global` to `window` by default but this can be overridden using the `output.globalObject` configuration. Are you able to check if your build configuration is setting the global object to something other than `window`?

If you are using Webpack yourself it may also be worth a try setting 'ably' as a [webpack external](https://webpack.js.org/configuration/externals/). If you are using a different bundler there is likely an equivalent option you can use.

I tried importing Ably in a next project using create-next-app and didn't see this error so I'm not able to reproduce the behaviour locally at the moment.

**Comment by tencircles** [comment]
@owenpearson I created a #883 with the suggested fix. Still unsure of the cause after poking around a bit.

**Comment by owenpearson** [comment]
@tencircles Yeah that is rather odd.

I do take your point about the `global.setImmediate` check, thanks a lot for opening the PR 🙂
